# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ConfigurableSearch
                                 A QGIS plugin
 Attribute search based on config file
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-01
        copyright            : (C) 2020 by Zoltan Siki
        email                : siki1958@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ConfigurableSearch class from file ConfigurableSearch.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .configurable_search import ConfigurableSearch
    return ConfigurableSearch(iface)
